# Generated by Django 5.0.2 on 2024-03-24 00:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'offre'), (1, 'demande')])),
                ('date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(default='Non definie', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.poste')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.poste', models.Model),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.poste')),
                ('localisation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.poste', models.Model),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.poste')),
                ('text', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.poste', models.Model),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.poste')),
                ('typestg', models.IntegerField(choices=[(1, 'ouvrier'), (2, 'tachnicien'), (3, 'PFE')])),
                ('societe', models.CharField(max_length=100)),
                ('duree', models.IntegerField()),
                ('sujet', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.poste', models.Model),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.poste')),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('heuredep', models.TimeField()),
                ('nbsiege', models.IntegerField()),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.poste', models.Model),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Non definie')),
                ('like', models.BooleanField()),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Studenthelp.poste')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Studenthelp.user')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Studenthelp.user'),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.evenement')),
                ('club', models.CharField(max_length=100)),
            ],
            bases=('Studenthelp.evenement', models.Model),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Studenthelp.evenement')),
                ('prix', models.FloatField()),
            ],
            bases=('Studenthelp.evenement', models.Model),
        ),
    ]
