# Generated by Django 5.0.2 on 2024-03-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.CharField(choices=[('0', 'offre'), ('1', 'demande')], max_length=100),
        ),
    ]
