# Generated by Django 5.0.2 on 2024-03-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0002_alter_poste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.CharField(choices=[('0', 'offre'), ('1', 'demande')], default='0', max_length=1),
        ),
    ]
