# Generated by Django 5.0.2 on 2024-03-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0005_alter_poste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.IntegerField(choices=[('offre', 0), ('demande', 1)], default='0'),
        ),
    ]
