# Generated by Django 5.0.2 on 2024-03-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0006_alter_poste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='typestg',
            field=models.IntegerField(choices=[('ouvrier', 1), ('tachnicien', 2), ('PFE', 3)]),
        ),
    ]
