# Generated by Django 5.0.2 on 2024-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0007_alter_stage_typestg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.IntegerField(choices=[(0, 'offre'), (1, 'demande')], default='0'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='duree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='typestg',
            field=models.IntegerField(choices=[(1, 'ouvrier'), (2, 'tachnicien'), (3, 'PFE')]),
        ),
    ]
