# Generated by Django 5.0.2 on 2024-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0010_alter_reaction_comment_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Enter your password', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Enter your username', max_length=100),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='comment',
            field=models.TextField(default='Non definie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Non definie', max_length=254),
        ),
    ]
