# Generated by Django 5.0.2 on 2024-05-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenthelp', '0012_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Studenthelp.poste'),
        ),
    ]
